name: EasyHomes
version: 1.0.0
main: com.easyhomes.EasyHomes
author: Bishyy
website: https://discord.gg/mkyU3SgBUP
description: Professional home management system with MySQL, cache, economy and integrations
api-version: 1.13
softdepend: [Vault, PlaceholderAPI, WorldGuard]

commands:
  home:
    description: Teleport to your home
    usage: /<command> [name]
    aliases: [h]
  sethome:
    description: Set a home at your current location
    usage: /<command> <name>
  delhome:
    description: Delete a home
    usage: /<command> <name>
    aliases: [removehome, remhome]
  easyhomes:
    description: EasyHomes admin commands
    usage: /<command> <reload|debug>
    aliases: [eh, ehomes]

permissions:
  easyhomes.*:
    description: All EasyHomes permissions
    children:
      easyhomes.home: true
      easyhomes.sethome: true
      easyhomes.delhome: true
      easyhomes.bypass.cooldown: true
      easyhomes.bypass.combat: true
      easyhomes.bypass.cost: true
      easyhomes.unlimited: true
      easyhomes.reload: true
      easyhomes.debug: true
  easyhomes.home:
    description: Allow using /home command
    default: true
  easyhomes.sethome:
    description: Allow using /sethome command
    default: true
  easyhomes.delhome:
    description: Allow using /delhome command
    default: true
  easyhomes.reload:
    description: Allow reloading configuration
    default: op
  easyhomes.debug:
    description: Allow enabling debug mode
    default: op
  easyhomes.bypass.cooldown:
    description: Bypass teleport cooldown
    default: op
  easyhomes.bypass.combat:
    description: Bypass combat tag restriction
    default: op
  easyhomes.bypass.cost:
    description: Bypass economy costs
    default: op
  easyhomes.limit.1:
    description: Allow 1 home
    default: true
  easyhomes.limit.3:
    description: Allow 3 homes
    default: false
  easyhomes.limit.5:
    description: Allow 5 homes
    default: false
  easyhomes.limit.10:
    description: Allow 10 homes
    default: false
  easyhomes.limit.15:
    description: Allow 15 homes
    default: false
  easyhomes.limit.25:
    description: Allow 25 homes
    default: false
  easyhomes.limit.50:
    description: Allow 50 homes
    default: false
  easyhomes.unlimited:
    description: Unlimited homes
    default: op
